config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'splash#index'

  resources :splash, only: %i[index]

  resources :users, only: %i[index show new create destroy] do
    resources :categories, only: %i[index new edit show  update create destroy] do
      resources :posts, only: %i[index new edit show update create destroy]
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  validates :title, presence: true, length: { minimum: 3, maximum: 25 }

  belongs_to :user
  has_many :posts, dependent: :destroy
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { minimum: 3, maximum: 25 }
  validates :desc, presence: true
  has_rich_text :desc

  belongs_to :user
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, presence: true, length: { minimum: 3, maximum: 25 }
  validates :last_name, presence: true, length: { minimum: 3, maximum: 25 }
  validates :address, presence: true, length: { minimum: 3, maximum: 100 }
  validates :role, presence: true, length: { minimum: 3, maximum: 25 }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :categories, dependent: :destroy
  has_many :posts, through: :categories, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name address role phone_number password email])
  end

  def after_sign_out_path_for(_resource)
    session[:previous_url] || root_path
  end

  def after_sign_in_path_for(_resource)
    session[:previous_url] || user_categories_path(current_user.id)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: %i[show edit update destroy]
  before_action :set_user, only: %i[index show create edit destroy]

  def index
    @categories = Category.all
  end

  def show; end

  def edit; end

  def new
    @category = Category.new
  end

  def update
    if @category.update(category_params)
      redirect_to user_categories_path, notice: 'Category was successfully updated.'
    else
      render :edit
    end
  end

  def create
    @category = Category.new(user_id: @user, **category_params)
    @category.user_id = current_user.id

    if @category.save
      redirect_to user_categories_path, notice: 'Category was successfully created.'
    else
      redirect_to user_categories_path, notice: 'Category was not created.'
    end
  end

  def destroy
    @category.destroy
    redirect_to user_categories_path, notice: 'Category was successfully destroyed.'
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def set_user
    @user = current_user
  end

  def category_params
    params.require(:category).permit(:title)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: %i[show edit update destroy]
  before_action :set_category, only: %i[index new create]

  def index
    @posts = Post.all.with_rich_text_desc
  end

  def show; end

  def edit; end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.category_id = params[:category_id]
    if @post.save
      redirect_to user_category_posts_path, notice: 'post was successfully created.'
    else
      render :new
    end
  end

  def update
    if @post.update(post_params)
      redirect_to user_category_posts_path, notice: 'post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to user_category_posts_path, notice: 'post was successfully destroyed.'
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def set_category
    @category = params[:category_id]
  end

  def post_params
    params.require(:post).permit(:title, :desc)
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  before_action :authenticate_user!, except: %i[index]
  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: %i[show edit update]

  def index
    @users = User.all
  end

  def show; end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/categories/_form.html.erb
<%= form_with model: @category, class: "bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4", url: "#{action_name == 'edit'? user_category_path : user_categories_path(current_user.id)}" , data: { turbo_method: :post }, data: { turbo_scope: :post } do |f| %>
    <div class="mb-6 m-4">
      <label for="Category Title" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Category Title</label>
      <%= f.text_field :title,  class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
    </div>
     <%= f.submit "#{action_name == 'edit' ? "Update Category": "Add New Category" }", class: "m-4 bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
<% end %>

app/views/categories/edit.html.erb
<div class="container flex flex-col justify-center">
  <%= render 'form'%>
</div>

app/views/categories/index.html.erb
<div class="container flex flex-col space-y-2">
  <div class="flex flex-col	place-items-end mr-4">
    <%= link_to "Add New Category", new_user_category_path(current_user.id), class: "right-0 mt-4 bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded" %>
  </div>
  <div class=" container px-2 flex justify-center mt-4">
    <ul class="bg-white rounded-lg border border-gray-200 w-full text-gray-900">
    <% @categories.each do |category| %>
      <li class="flex justify-between place-content-around px-6 py-4 border-b border-gray-200 w-full">
        <%= link_to category.title, user_category_posts_path(current_user.id,category.id), class: "text-gray-900 hover:text-gray-900 focus:text-gray-900" %>
        <div class="flex space-x-3 justify-center">
          <%= link_to "Edit", edit_user_category_path(current_user.id,category.id), class: "text-gray-900 hover:text-gray-900 focus:text-gray-900" %>
          <%= link_to "Delete", user_category_path(current_user.id,category),  data: { turbo_method: :delete }, class: "text-gray-900 hover:text-gray-900 focus:text-gray-900" %>
        </div>
      </li>
    <% end %>
    </ul>
  </div>
</div>

app/views/categories/new.html.erb
<div class="container flex flex-col justify-center">
<% if notice %>
  <p class="notice"><%= notice %></p>
<% end %>
  <%= render 'form'%>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AljamaatLibrary</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application" %>
  </head>

  <body>
    <main class="container w-full mx-auto mt-0 flex-col">
      <%= render "shared/navbar" %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </main>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: @post, local: true, url: "#{action_name == 'edit' ? user_category_post_path : user_category_posts_path }", data: { turbo_method: :post }, data: { turbo_scope: :post } do |f| %>
    <div class="mb-6 m-4">
      <label for="Post Title" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Category Title</label>
      <%= f.text_field :title, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
    </div>

    <div class="mb-6 m-4">
      <label for="Description" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Description</label>
      <%= f.rich_text_area :desc, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
    </div>
     <%= f.submit "#{action_name == 'edit' ? 'Update Postt': 'Add New Post'}", class: "m-4 bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
<% end %>

app/views/posts/edit.html.erb
<div class="container flex flex-col justify-center">
<% if notice %>
  <p class="notice"><%= notice %></p>
<% end %>
  <%= render 'form'%>
</div>

app/views/posts/index.html.erb
<div class="container flex flex-col space-y-2">
  <div class="flex flex-col	place-items-end mr-4">
    <%= link_to "Add New Post", new_user_category_post_path(current_user.id), class: "right-0 mt-4 bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded" %>
  </div>
  <div class=" container px-2 flex justify-center mt-4">
    <ul class="bg-white rounded-lg border border-gray-200 w-full text-gray-900">
    <% @posts.each do |post| %>
      <li class=" flex justify-between place-content-around px-6 py-4 border-b border-gray-200 w-full">
        <%= link_to post.title, user_category_post_path(current_user.id, @category, post.id), data: { turbo_method: :get }, class: "text-gray-900 hover:text-gray-900 focus:text-gray-900" %>
        <div class="flex space-x-3 justify-center">
          <%= link_to "Edit", edit_user_category_post_path(current_user.id, @category, post.id), class: "text-gray-900 hover:text-gray-900 focus:text-gray-900" %>
          <%= link_to "Delete", user_category_post_path(current_user.id, @category, post.id), data: { turbo_method: :delete }, class: "text-gray-900 hover:text-gray-900 focus:text-gray-900" %>
        </div>
      </li>
    <% end %>
    </ul>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container flex flex-col space-y-2">
<% if notice %>
  <p class="notice"><%= notice %></p>
<% end %>
  <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div class="container flex flex-col space-y-2">
    <div class="mb-6 m-4">
        <div class="container flex flex-row text-center justify-center font-bold text-lg m-4"> <h1><%= @post.title %></h1> </div>
        <div class="contianer flex flex-col text-right"><%= @post.desc%></div>
    </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="relative w-full flex flex-wrap items-center justify-between py-4 bg-gray-100 text-gray-500 hover:text-gray-700 focus:text-gray-700 shadow-lg">
  <div class="container-fluid w-full flex flex-wrap items-center justify-between px-6">
    <div class="container-fluid flex">
      <a class="flex items-center text-gray-900 hover:text-gray-900 focus:text-gray-900 mt-2 lg:mt-0 mr-1" href="#">
        <%= image_tag("logo.png", size: "30x30", alt: "Edit Entry") %>        
        <% if current_user %>
        <span class="font-medium ml-3"><%= current_user.first_name %> <%= current_user.last_name %></span>
        <% else %>
        <span class="font-medium ml-3">MDBootstrap</span>
        <% end %>
      </a>
      <% if user_signed_in? %>
        <%= link_to 'Back', 'javascript:history.back()', class: "flex absolute ml-3 right-0 items-center text-gray-900 hover:text-gray-900 focus:text-gray-900 mt-2 lg:mt-0 mr-[90px]" %>
        <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class: "flex absolute ml-3 right-0 items-center text-gray-900 hover:text-gray-900 focus:text-gray-900 mt-2 lg:mt-0 mr-3" %>
      <% else %>
        <%= link_to "Log in", new_user_session_path, class: "flex absolute  ml-3 right-0 items-center text-gray-900 hover:text-gray-900 focus:text-gray-900 mt-2 lg:mt-0 mr-5" %>
      <% end %>
    </div>
  </div>
</nav>

app/views/splash/index.html.erb
<div class="flex flex-col">
<% if current_user %>
  <% user_categories_path(current_user.id) %>
<% else %>
  <div class="flex text-center justify-center">
    <div class="logo">
      <%= image_tag("logo.png", size: "200x200", alt: "Edit Entry", class: "mt-4 animate-pulse") %>
    </div>
  </div>
  <div class="flex space-x-4 justify-center mt-[200px]">
     <%= link_to "Login", new_user_session_path, class: "inline-block px-10 py-2.5 bg-blue-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out" %>
     <%= link_to "Singup", new_user_registration_path, class: "inline-block px-10 py-2.5 bg-blue-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out" %>
  </div>
  
</div>
<% end %>

app/views/users/index.html.erb
<div class="container flex-col">
  <div class="splash">
    <div class="splash__logo">
      <img src="https://mdbootstrap.com/img/logo/mdb-transaprent-noshadows.png" alt="" loading="lazy" />
    </div>
    <div class="splash__links">
      <a href="https://mdbootstrap.com/docs/standard/" target="_blank" class="btn btn-primary">Documentation</a>
      <a href="https://mdbootstrap.com/docs/standard/getting-started/quick-start/" target="_blank" class="btn btn-primary">Quick start</a>
    </div>
  </div>
</div>